update-tbilisi-feed:
    image: docker.io/rust
    before_script:
        - apt update
        - apt install zip sqlite3 libzip5 bzip2 pkg-config protobuf-compiler -y
    script:
        - cargo run --release --bin gtfs-static -- -o gtfs.zip
        - if [ ! -z "$WEBDAV_PASSWORD" ]; then curl -X PUT --data-binary @gtfs.zip -u gtfs:"$WEBDAV_PASSWORD" https://jbb.ghsq.de/gtfs/ge-tbilisi.gtfs.zip; fi
